baseURL = "https://investigandoando.com/"
languageCode = "es"
DefaultContentLanguage = "es"
title = "InvestigandoAndo"
theme = "anatole"
summarylength = 10
enableEmoji = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "Soy Sami Arancibia"
author = "Samanta Arancibia"
description = "e investigando ando :)"
profilePicture = "images/sami.png"
keywords = ""
favicon = "favicons/"
customCss = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://de.linkedin.com/"

#[[params.socialIcons]]
#icon = "fa-github"
#title = "GitHub"
#url = "https://github.com/lxndrblz/anatole/"

[[params.socialIcons]]
icon = "fa-instagram"
title = "instagram"
url = "https://www.instagram.com/"

#[[params.socialIcons]]
#icon = "fa-envelope"
#title = "e-mail"
#url = "mailto:sami.arancibia@gmail.com"

[[params.socialIcons]]
name = "Twitter"
icon = "fab fa-twitter fa-2x"
#weight = 3
url = "https://twitter.com/sami_arancibia"

## Menu items

[menu]

  [[menu.main]]
  name = "Inicio"
  identifier = "inicio"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "Acerca de"
  weight = 300
  identifier = "acerca-de"
  url = "/acerca-de/"